init:
  model: 'FinalModel'
  optimizer: 'Adam'
  batch_size: 8
  epochs: 15

transforms:
  img_size: 64

hyperparams:
  learning_rate: 0.0001
  betas: [0.9, 0.999]
  epsilon: 1.0e-8
  weight_decay: 0.00001
  momentum: 0.0
  nesterov: False